### ISSUE TITLE
DBW Node

### ISSUE THREAD

**Issue by ahmedkhalaf** [ahmedkhalaf/CarND-Capstone#3]
Once your waypoint updater is publishing /final_waypoints, the waypoint_follower node will start publishing messages to the/twist_cmd topic. At this point, you have everything needed to build the dbw_node. After completing this step, the car should drive in the simulator, ignoring the traffic lights.

**Comment by danielwo** [comment]
[flit](https://github.com/ahmedkhalaf/CarND-Capstone/blob/3f5e0500bbbf73b84a0b5439cc02f48cf5014d59/ros/src/twist_controller/twist_controller.py#L58)  typo.

Also having issues with the steering module not working.

**Comment by ahmedkhalaf** [comment]
Thanks, @danielwo .. fixed in changeset 9925a1e
Now the car is driving more normally but running all red lights

**Comment by danielwo** [comment]
If you are using the classifier, I believe the issue is the classifier is just too slow. One way to try to get this to work is changing STATE_COUNT_THRESHOLD = 1  (this makes it more responsive but less robust) in tl_detector.py   as well as increasing LOOKAHEAD_WPS = 70 or 100 in waypoint_updater.py to give a longer time to be able to classify.

Another possible help could be to change the image classification in image_cb (under tl_detector.py) to classify every image or every 2nd image. With these it is somewhat responsive, but I still see some issues.
