### ISSUE TITLE
Waypoint Updater with Mockup Updates

### ISSUE THREAD

**Issue by ahmedkhalaf** [ahmedkhalaf/CarND-Capstone#5]
Use data coming from Mockup Traffic Light Waypoint - the car should drive in the simulator, stopping at traffic lights (but not able to detect them, yet).

**Comment by ahmedkhalaf** [comment]
@danielwo are you planning to use the TL state and stop line info coming from the simulator?

**Comment by danielwo** [comment]
It appears my implementation (basically the same as the walkthrough) is already comitted to the repo via #7 (given that it is a full waypoint updater). It uses only the /traffic_waypoint topic which gets its info based on the TL state  (from simulator or detector) and stop line info from the simulator. We can use the stop line info, but the TL state will eventually need to be replaced with an actual classifier, because the TL state in /vehicle/traffic_lights won't be available on test.

The /traffic_waypoint topic is published via the image_cb in tl_detector.py

Should I commit the TLDetector instead? (I think someone is already working on it however). It is a bit ambiguous as to what refers to what. It may be that this issue is just redundant with respect to #7
